baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'tansawit'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "A smol blog"

# Appearance settings
theme = 'light'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I'm Sawit. Currently, I'm the Head of Integrations at [Initia](https://initia.xyz/), focusing on onboarding new teams and developer into the ecosystem and building developer and user tooling products.

Before that, amongst other things,I was the Founder & CEO of Alles Labs building [Celatone](https://celat.one/) (acq. by [Initia](https://initia.xyz/)) and previously the Integration Lead at [Band Protocol](https://bandprotocol.com/).
"""

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "twitter"
url = "https://twitter.com/tansawit"

[[params.social]]
name = "github"
url = "https://github.com/tansawit"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/tansawit"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'github'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"
